### PR TITLE
make fannkuchredux multithreaded

### PR DESCRIPTION
**Pull request by hycakir**
Transliterated, gives slightly slower performance than the Java implementation.

https://github.com/KristofferC/BenchmarksGame.jl/issues/5

### CODE REVIEW

**Comment by SimonDanisch** [comment]
>gives slightly slower performance than the Java implementation.

I think we can add quite a few inbounds to spice things up ;)

**Comment by KristofferC** [comment]
Can we call this file `fannkuchredux-fast.jl`. I'd like us to keep the existing methods for a while to have a baseline.

**Comment by KristofferC** [comment]
Pushed it to master.

**Comment by KristofferC** [comment]
```
 ────────────────────────────────────────────────
 Section                   ncalls     time   %tot
 ────────────────────────────────────────────────
 fannkuchredux                  1    36.6s   100%
   fannkuchredux.jl             1    30.0s  82.0%
   fannkuchredux-fast.jl        1    6.48s  17.7%
 ────────────────────────────────────────────────%
```

**Pull request closed without merging**
